dic =   {
        "A": "Alanina",
        "R": "Arginina", 
        "N": "Aspargina", 
        "D": "Aspártico", 
        "C": "Cisteina", 
        "E": "Glutámico", 
        "Q": "Glutamina", 
        "G": "Glicina", 
        "H": "Histeina", 
        "I": "Isoleucina", 
        "L": "Leucina", 
        "K": "Lisina", 
        "M": "Metionina", 
        "F": "Fenilalanina", 
        "P": "Prolina", 
        "S": "Serina", 
        "T": "Treonina", 
        "W": "Triptófano", 
        "Y": "Tirosina", 
        "V": "Valina" 
        }